DjangoWebProject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from app import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DjangoWebProject.views.home', name='home'),
    #url(r'^app/', include('app.urls')),

    url(r'', include('app.urls', namespace = "app")),
    url(r'^admin/', include(admin.site.urls)),
)

app/urls.py
from django.conf.urls import patterns, url
from app import views

urlpatterns = patterns('',
    url(r'^$', views.index, name = "index"),
    url(r'^(?P<blankErrorStatus>\w+)/createAccount/$', views.createAccount, name = 'createAccount'),

    url(r'^(?P<blankErrorStatus>\w+)/createOrder/$', views.createOrder, name = 'createOrder'),
    url(r'^addOrder/$', views.addOrder, name = 'addOrder'),
    url(r'^addUser/$', views.addUser, name = 'addUser'),

    url(r'^logInPage/$', views.logInPage, name = 'logInPage'),
    url(r'^logInAuthenticate/$', views.logInAuthenticate, name = "logInAuthenticate"),
    url(r'^logout/$', views.logout, name = 'logout'),

    url(r'^orders/$', views.viewOrders, name = "viewOrders"),
    url(r'^(?P<id>\w+)/claimOrder/$', views.claimOrder, name = "claimOrder"),
)

app/models.py
from django.db import models

#User model represents user accounts
class User(models.Model):
	firstName = models.CharField(max_length = 50)
	lastName = models.CharField(max_length = 50)
	username = models.CharField(max_length = 50)
	hashedPassword = models.CharField(max_length = 50)
	phoneNumber = models.CharField(max_length = 50)
	email = models.CharField(max_length = 50)

	#Represents User as a string when it is called
	def __str__(self):
		return self.firstName

	#Orders the Users in the database by first name
	class Meta:
		ordering = ('firstName',)

# Order model for placed orders
class Order(models.Model):
	user = models.ForeignKey(User)
	restaurant = models.CharField(max_length = 50)
	food = models.CharField(max_length = 50)
	time = models.DateTimeField('time placed')
	user_location = models.CharField(max_length = 50)
	runner = models.IntegerField()

	# Represents order as a string
	def __str__(self):
		return "%s from %s to %s at %s" % (self.food, self.restaurant, self.user, self.user_location)

	#Orders the Users in the database by first name
	class Meta:
		ordering = ('time',)

app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
import hashlib
from app.models import *
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.core.mail import send_mail

def index(request):
	if ('user_id' in request.session):
		currentUser = User.objects.get(id = request.session['user_id'])
		context = {'currentUser': currentUser}
		return render(request, 'app/index.html', context)
	else:
		return render(request, 'app/index.html')

# View orders page
def viewOrders(request):
	if ('user_id' in request.session):
		currentUser = User.objects.get(id = request.session['user_id'])
		orderList = Order.objects.all()
		context = {'currentUser': currentUser, 'orderList': orderList}
		return render(request, 'app/orders.html', context)
	else:
		return render(request, 'app/logInPage.html')

#Create account page with form
def createAccount(request, blankErrorStatus):
	#Determines the error based on the URL string
	if blankErrorStatus == "True":
		context = {'error': False, 'blankErrorStatus': True}
	else:
		context = {'error': False, 'blankErrorStatus': False}
	return render(request, 'app/createAccount.html', context)

def sendRunnerMessage(runner, client, order):
	clientName = client.firstName
	clientNumber = client.phoneNumber
	runnerEmail = runner.email
	food = order.food
	restaurant = order.restaurant
	location = order.user_location
	body = "You are getting %s from %s for delivery to %s at %s. You can reach them at %s" % (food, restaurant, clientName, location, clientNumber)
	send_mail("CMYum Order", body, 'cmyumorders@gmail.com', [runnerEmail], fail_silently=False)

def sendClientMessage(runner, client, order):
	runnerName = runner.firstName
	runnerNumber = runner.phoneNumber
	clientEmail = client.email
	body = "%s is getting your order! You can reach them at %s" % (runnerName, runnerNumber)
	send_mail("CMYum Order", body, 'cmyumorders@gmail.com', [clientEmail], fail_silently=False)

def removePunctuation(s):
	result = ''
	for char in s:
		if char in '0123456789':
			result += char
	return result

#Adds a user account to the database
def addUser(request):
	firstName = request.POST['First_Name']
	lastName = request.POST['Last_Name']
	username = request.POST['username']
	phoneNumber = request.POST['phoneNumber']
	emailAddress = request.POST['email']
	password = request.POST['password']

	phoneNumber = removePunctuation(phoneNumber)

	#Password is encrypted by hashing
	encryptedPassword = hashlib.sha1(password).hexdigest()
	#If username already exists in database, then raises an error in the
	#createAccount page
	try:
		User.objects.get(username = username)
		context = {'error': True, 'blankErrorStatus': False}
		return render(request, 'app/createAccount.html', context)
	except:
		#If one or more fields are blank, raises an error
		if (firstName == "" or lastName == "" or username == "" or password == ""
			or phoneNumber == "" or emailAddress == ""):
			blankErrorStatus = True
			###Probably not the best idea to redirect here, use render with context instead
			return HttpResponseRedirect(reverse('app:createAccount', args=(blankErrorStatus,)))
		else:
			#If the username does not exist and all fields are filled, creates a
			#new User instance
			newUser = User(firstName = firstName, lastName = lastName,
				username = username, hashedPassword = encryptedPassword, phoneNumber = phoneNumber,
				email = emailAddress)
			newUser.save()
			return HttpResponseRedirect(reverse('app:index'))


# Creates order page with form
def createOrder(request, blankErrorStatus):
	#Determines the error based on the URL string
	if 'user_id' in request.session:
		user = User.objects.get(id = request.session['user_id'])
		if blankErrorStatus == "True":
			context = {'user': user, 'error': False, 'blankErrorStatus': True}
		else:
			context = {'user': user, 'error': False, 'blankErrorStatus': False}
		return render(request, 'app/createOrder.html', context)
	else:
		return render(request, 'app/logInPage.html')

#Adds an order to the database
def addOrder(request):
	# Figure out how to get username (username not in form)
	# For now, enter username manually
	user = User.objects.get(id = request.session['user_id'])
	restaurant = request.POST['Restaurant']
	food = request.POST['Food']
	# Gets time from django.utils timezone
	time = timezone.now()
	user_location = request.POST['Location']
	runner = -1
	#createAccount page
	#If one or more fields are blank, raises an error
	if (restaurant == "" or food == "" or user_location == ""):
		blankErrorStatus = True
		###Probably not the best idea to redirect here, use render with context instead
		return HttpResponseRedirect(reverse('app:createOrder', args=(blankErrorStatus,)))
	else:
		#If the username does not exist and all fields are filled, creates a
		#new User instance
		newOrder = Order(user = user, restaurant = restaurant, food = food, time = time,
						 user_location = user_location, runner = runner)
		newOrder.save()
		return HttpResponseRedirect(reverse('app:index'))

#Log In page with form
def logInPage(request):
	context = {'error': False}
	return render(request, 'app/logInPage.html', context)

#Verifies that the username and password entered are in the database
def logInAuthenticate(request):
	username = request.POST['username']
	password = request.POST['password']
	encryptedPassword = hashlib.sha1(password).hexdigest()
	try:
		#If username is in database and matches with password, go to
		#userProfile page
		currentUser = User.objects.get(username = username)
		if (encryptedPassword == currentUser.hashedPassword):
			request.session['user_id'] = currentUser.id
			return HttpResponseRedirect(reverse('app:index'))
		#If username is in database but password is incorrect, raises an error
		#in the logInPage
		else:
			context = {'error': True, 'username': username}
			return render(request, 'app/logInPage.html', context) 
	except:
		#If username is not in database, raises an error in the
		##logInPage
		context = {'error': True}
		return render(request, 'app/logInPage.html', context) 

def claimOrder(request, id):
	currentOrder = Order.objects.get(id=id)
	runner = User.objects.get(id = request.session['user_id'])
	sendRunnerMessage(runner, currentOrder.user, currentOrder)
	sendClientMessage(runner, currentOrder.user, currentOrder)
	currentOrder.delete()
	return HttpResponseRedirect(reverse('app:viewOrders'))

#Allows users to log out of their session
def logout(request):
	#Deketes the cookie storing user info
	del request.session['user_id']
	return HttpResponseRedirect(reverse('app:index'))

app/templates/app/createAccount.html
<!DOCTYPE html>
<html>
	<head>
	  	{% load staticfiles %}
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">
	    <link rel="icon" href="">
	    <!--"Normalizes" the styling across browsers"-->
	    <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css">
	    <!--jQuery file -->
	    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	    <!--Bootstrap core JS -->
	    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	    <!-- Bootstrap core CSS -->
	    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	    <!--Custom styles-->
		<link rel="stylesheet" type="text/css" href="">
		<title>CMYum</title>
	</head>

	<body>
		<h1>Create an Account</h1>
		<!--Request sent to addUser-->
		<form action = "{% url 'app:addUser' %}" method="post">
		<div class="form-group">
		{% csrf_token %}
			<div class="col-sm-3">
				<label for="firstNameInput">First Name</label>
				<input type="text" name = "First_Name" class="form-control" id="firstNameInput">
				<br>
				<label for="lastNameInput">Last Name</label>
				<input type="text" name = "Last_Name" class="form-control" id="lastNameInput">
				<br>
				<label for="usernameInput">Username</label>
				<input type="text" name = "username" class="form-control" id="usernameInput">
				{% if error == True %}
					That username already exists.
					<br>
				{% endif %}
				<br>
				<label for="phoneNumberInput">Phone Number</label>
				<input type="text" name = "phoneNumber" class="form-control" id="phoneNumberInput">
				<br>
				<label for="emailInput">Email</label>
				<input type="text" name = "email" class="form-control" id="emailInput">
				<br>
				<label for="passwordInput">Password</label>
				<input type="password" name = "password" class="form-control" id="passwordInput">
				{% if blankErrorStatus == True %}
					Please fill out all the fields.
					<br>
				{% endif %}
				<br>
				<button type="submit" class="btn btn-primary btn-md">Create Account</button></a>
			</div>
		</div>
		</form>
	</body>
</html>

app/templates/app/createOrder.html
<h1>Place an Order</h1>
<h2>Hi {{user.firstName}}</h2>
<!--Request sent to addOrder-->
<form action = "{% url 'app:addOrder' %}" method="post">
<div class="form-group">
{% csrf_token %}
	<div class="col-md-8">
		<!--Fix this to automatically get username-->
		<label for="restaurantInput">Restaurant Name</label>
		<input type="text" name = "Restaurant" class="form-control" id="restaurantInput">
		<br>
		<label for="foodInput">Food</label>
		<input type="text" name = "Food" class="form-control" id="foodInput">
		<br>
		<label for="userLocation">Location</label>
		<input type="text" name = "Location" class="form-control" id="userLocation">
		{% if blankErrorStatus == True %}
			Please fill out all the fields.
			<br>
		{% endif %}
		<br>
		<button type="submit" class="btn btn-primary btn-md">Place Order </button></a>
	</div>
</div>
</form>

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>CMYum</title>


    <!-- Bootstrap core CSS -->
    {% load staticfiles%}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/index.css" %}" rel="stylesheet">

  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">CMYum</h3>
              <nav>
                <ul class="nav masthead-nav">
                  {% if currentUser = null %}
                    <li><a href = "{% url 'app:createAccount' blankErrorStatus=False %}">Create Account</a></li>
                  {% else %}
                    <li class="active"><a>Hi {{currentUser.firstName}}</a></li>
                  {% endif %}

                  {% if currentUser = null %}
                    <li><a href = "{% url 'app:logInPage' %}">Log In</a></li>
                  {% else %}
                    <li><a href = "{% url 'app:logout' %}">Log Out</a></li>
                  {% endif %}
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Fill your Yum!</h1>
            <p class="lead">CMYum is a crowdsourced food delivery service that connects hungry appetites with enterprising individuals.</p>
            <p class="lead">
              <a href="{% url 'app:createOrder' blankErrorStatus=False %}" class="btn btn-lg btn-default">Place an Order</a>
            </p>
            <p class="lead">
              <a href="{% url 'app:viewOrders' %}" class="btn btn-lg btn-default">View Order</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>By Shouvik Mani, David Simon, Sam Westenberg, and Chris Smith</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>

app/templates/app/logInPage.html
<!DOCTYPE html>
<html>
	<head>
	  	{% load staticfiles %}
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">
	    <link rel="icon" href="">
	    <!--"Normalizes" the styling across browsers"-->
	    <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css">
	    <!--jQuery file -->
	    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	    <!--Bootstrap core JS -->
	    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	    <!-- Bootstrap core CSS -->
	    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	    <!--Custom styles-->
		<link rel="stylesheet" type="text/css" href="">
		<title>CMYum</title>
	</head>

	<body>
		<h1>Log In</h1>
		<!--Request sent to logInAuthenticate-->
		<form action = "{% url 'app:logInAuthenticate' %}" method = "post">
			{% csrf_token %}
			<div class="col-sm-3">
				<div class="form-group">
					<label for="usernameInput">Username</label>
					{% if username %}
						<input type="text" name = "username" class="form-control" id="usernameInput" value="{{username}}">
					{% else %}
						<input type="text" name = "username" placeholder="Username" class="form-control" id="usernameInput">
					{% endif %}
					<br>
					<label for="passwordInput">Password</label>
					<input type="password" name = "password" placeholder="Password" class="form-control" id="passwordInput">
					<br>
					{% if error == True %}
						Invalid username or password. Please try again.
						<br><br>
					{% endif %}
					<button type="submit" class="btn btn-primary btn-md">Log In</button></a>
				</div>
			</div>
		</form>
	</body>
</html>

app/templates/app/orders.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    {% load staticfiles%}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Woooo!</h1>
    {% if currentUser %}
      Hi {{currentUser.firstName}}
    {% endif %}
    <a href = "{% url 'app:createAccount' blankErrorStatus=False %}">Create Account</a>
    <a href = "{% url 'app:createOrder' blankErrorStatus=False %}">Place an Order</a>
    {% if currentUser = null %}
      <a href = "{% url 'app:logInPage' %}">Log In</a>
    {% endif %}

    <ul>
    {% for order in orderList %}
    <li>{{ order }}</li>
    <a href="{% url 'app:claimOrder' id=order.id%}" class="btn btn-sm btn-default">Claim Orders</a>
    {% endfor %}
    </ul>

    {% if currentUser %}
      <a href = "{% url 'app:logout' %}">Log Out</a>
    {% endif %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>